- name: Download release assets  
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    mkdir assets
    assets_url=$(curl -s https://api.github.com/repos/fatedier/frp/releases/latest | jq -r '.assets_url')
    for asset_url in $(curl -s $assets_url | jq -r '.[].browser_download_url'); do
      filename=$(basename $asset_url)
      curl -JOL $asset_url -o assets/$filename
    done
